# This docker-compose file is used to run Elasticsearch and MongoDB for local development.
# It was copied from src/main/docker/docker-compose.yml in the spring boot project root.
# Any changes should be reflected in both files.
# TODO: Consider merging these two files into one to avoid duplication and potential inconsistencies.
version: "3.7"
services:
  app:
    image: species-lists:local
    build:
      dockerfile: ./src/main/docker/lambda.Dockerfile
      context: .
    user: "1000"
    volumes:
      - ./config:/config
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: file:/config/lists-service-config.properties
      SPRING_AOT_ENABLED: true
      SPRING_APPLICATION_JSON: '{"management.endpoints.enabled-by-default":"false"}'
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mock-oauth2-server:
        condition: service_started
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0-arm64
    container_name: species-lists-elastic
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fs",
          "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  mongodb:
    image: mongo:8
    container_name: species-lists-mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my-super-secret-pw
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.5
    ports:
      - "9999:9999"
    environment:
      SERVER_PORT: 9999
    hostname: host.docker.internal

  namematching:
    image: ${DOCKER_REPO:-local}/inbo-vbp-namematching-service:dev
    networks:
      default:
    command:
      - /config/namematching-service/config.yml
    ports:
      - "9179:9179"
    volumes:
      - /home/stefan/Projects/Inbo/vlaams-biodiversiteitsportaal/config/namematching-service:/config/namematching-service:ro
volumes:
  mongo:
  elasticsearch:
