VITE_GRAPHQL_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/graphql
VITE_REINDEX_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/reindex
VITE_REMATCH_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/rematch
VITE_MIGRATE_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/migrate
VITE_HOME_URL=https://ala.org.au
VITE_OIDC_AUTH_PROFILE=https://natuurdata.dev.inbo.be/myprofile
VITE_SIGNUP_URL=https://auth-secure.auth.ap-southeast-2.amazoncognito.com/login
VITE_OIDC_REDIRECT_URL=https://natuurdata.dev.inbo.be/species-lists
;VITE_OIDC_AUTH_SERVER=https://auth-secure.auth.ap-southeast-2.amazoncognito.com
VITE_OIDC_AUTH_SERVER=https://auth-dev.inbo.be/realms/vbp/protocol/openid-connect/auth
VITE_OIDC_CLIENT_ID=vbp-branding
VITE_OIDC_SCOPE=openid profile email ala/attrs ala/roles
VITE_LOGO_URL=https://natuurdata.dev.inbo.be/images/logo.png
VITE_DELETE_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/delete
VITE_APP_MAPBOX_TOKEN=https://www.ala.org.au/app/uploads/2019/01/logo.png
VITE_UPLOAD_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/upload
VITE_APP_BIE_URL=https://natuurdata.dev.inbo.be/bie-index
VITE_DOWNLOAD_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/download
VITE_INGEST_URL=https://natuurdata.dev.inbo.be/api/v2/species-lists/ingest

; User roles are found in property 'role' (OIDC) or 'cognito:groups' (Cognito)
VITE_PROFILE_ROLES=cognito:groups

; User id is found in profile property 'userid' (OIDC) or 'cognito:username' (Cognito)
VITE_PROFILE_USERID=cognito:username

; Admin role is 'ROLE_ADMIN' (OIDC) or 'admin' (Cognito)
VITE_ADMIN_ROLE=admin
