server.servlet.context-path=/api/v2/species-lists
app.name=species-lists
app.description=${app.name} is a Spring Boot application
app.url=
app.ws-url=
app.cookie.domain=
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
elastic.host=elasticsearch:9200
springdoc.swagger-ui.path=
release.directory=/tmp/
release.s3.bucket=s3://lists/releases
release.s3.enabled=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
spring.mongodb.uri=mongodb://mongodb:27017/species-lists
spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=species-lists
constraints.file=file:/resources/constraints.json
userDetails.web.url=https://natuurdata.dev.inbo.be/user-details/
userDetails.api.url=https://natuurdata.dev.inbo.be
namematching.url=https://namematching.natuurdata.dev.inbo.be
biocache.api.url=https://natuurdata.dev.inbo.be/biocache-service
collectory.api.url=https://natuurdata.dev.inbo.be/collectory
bie.url=https://natuurdata.dev.inbo.be/bie-index
bie.images.url=https://natuurdata.dev.inbo.be/bie-index/ws/imageSearch/%s?rows=%s&start=%s
image.url=https://natuurdata.dev.inbo.be/image-service/image/%s/large

namematching.url=http://namematching:9179
namematching.serviceURL=http://namematching:9179
webservice.read.timeout=600000
webservice.connect.timeout=600000
webservice.jwt=true
webservice.jwt-scopes=users/read ala/attrs ala/internal
webservice.client-id=
webservice.client-secret=
server.forward-headers-strategy=framework

management.endpoint.health.group.readiness.include=ping

app.cookie.domain=natuurdata.dev.inbo.be
cors.domain=natuurdata.dev.inbo.be
