# Note a DevContainer setup is available in .devcontainer/docker-compose.yml
# which uses a version of this file, found in the spring boot project root.
# This version is kept for historical reasons and should only be used if really needed.
# Any changes should be reflected in both files.
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26-arm64
    container_name: species-lists-elastic
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
  mongodb:
    image: mongo:6.0
    container_name: species-lists-mongo
    restart: on-failure
    ports:
      - "27017:27017"
    extra_hosts:
      - "mock.localhost:mock-oauth2-server"
    volumes:
      - ./data/species-lists/mongo/db:/data/db
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
    hostname: host.docker.internal

  namematching:
    image: ${DOCKER_REPO:-local}/inbo-vbp-namematching-service:dev
    networks:
      default:
    command:
      - /config/namematching-service/config.yml
    ports:
      - "9179:9179"
    volumes:
      - ../vlaams-biodiversiteitsportaal/config/namematching-service:/config/namematching-service:ro
    environment:
      LOG_LEVEL: "WARN"

#  lists:
#    image: atlasoflivingaustralia/lists-service:latest
#    container_name: lists-service
#    volumes:
#      - type: bind
#        source: /data/lists-service/config/lists-service-config.properties
#        target: /data/lists-service/config/lists-service-config.properties
#      - /data/lists/tmp:/tmp
#    restart: on-failure
#    ports:
#      - "8080:8080"
volumes:
  mongodb_data_container:
  elasticsearch-data:
    driver: local
