app.name=species-lists
app.version=1.0.0
app.description=${app.name} is a Spring Boot application
app.cookie.domain=
# Fix HTTP Header Information Disclosure vulnerability - hide server version
server.server-header=
server.forward-headers-strategy=framework

spring.graphql.graphiql.enabled=false
spring.graphql.graphiql.path=/graphiql
elastic.host=elasticsearch:9200
elastic.username=""
elastic.password=""
elastic.auth.enabled=false
elastic.tls.enabled=false
springdoc.swagger-ui.path=
release.directory=/tmp/
release.s3.bucket=s3://lists/releases
release.s3.enabled=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.data.mongodb.uri=mongodb://admin:my-super-secret-pw@mongodb:27017?authSource=admin
spring.data.mongodb.database=species-lists
spring.data.mongodb.auto-index-creation=true

# springdoc.api-info.version=@project.version@

bie.url=http://atlas.localhost/bie-index/ws/species/%s
bie.images.url=http://atlas.localhost/image-service/ws/imageSearch/%s?rows=%s&start=%s
image.url=http://atlas.localhost/image-service/image/%s/large
namematching.url=http://namematching.atlas.localhost

security.jwt.userIdClaim=username
security.jwt.roleClaims=cognito:groups
security.jwt.rolesFromAccessToken=true

security.jwt.enabled=true
security.jwt.discovery-uri=http://mock-oauth2-server:9999/default/.well-known/openid-configuration
security.jwt.clientId=vin962smco7pbsn8gtr5b23hm
security.apikey.enabled=false

webservice.client-id: test
webservice.client-secret: test

# admin role and admin scope
security.admin.roles=ROLE_ADMIN,ROLE_EDITOR
security.m2m.scope=ala/internal
#migrate.url=https://lists-test.ala.org.au
migrate.url=https://natuudata.inbo.be/species-list
# userdetails
userDetails.web.url=https://userdetails.test.ala.org.au/
userDetails.api.url=https://api.test.ala.org.au/userdetails/cognito/

# validation constraints
constraints.file=file:/config/constraints.json
